# Generated by Django 5.1 on 2024-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
