# Generated by Django 5.1 on 2024-08-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_servicehistory_next_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='upcoming_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
